[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
remappings = ['@prb-math/=lib/prb-math/']

[dependencies]
forge-std = "1.9.6"
"@prb-math" = "4.1.0"
"@openzeppelin-contracts" = "5.2.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
